name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        default: '3.10'
        description: Python runtime version
        required: false
        type: string
    secrets:
      github-token:
        description: GitHub Token
        required: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    timeout-minutes: 5
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
